
.DEFAULT_GOAL := all


all: 
	cd Problem1 && $(MAKE)
	cd Problem2 && $(MAKE)
	cd Problem3 && $(MAKE)
	cd Problem4 && $(MAKE)
	cd Problem5 && $(MAKE)
	cd Problem6 && $(MAKE)
	cd Problem7 && $(MAKE)
	cd Problem8 && $(MAKE)
	cd Problem9 && $(MAKE)
	cd Problem10 && $(MAKE)
	cd Problem11 && $(MAKE)
	cd Problem12 && $(MAKE)
	cd Problem13 && $(MAKE)
	cd Problem14 && $(MAKE)
	cd Problem15 && $(MAKE)
	cd Problem16 && $(MAKE)
	cd Problem17 && $(MAKE)
	cd Problem18 && $(MAKE)
	cd Problem19 && $(MAKE)
	cd Problem20 && $(MAKE)
	cd Problem21 && $(MAKE)
	cd Problem22 && $(MAKE)
	cd Problem23 && $(MAKE)
	cd Problem24 && $(MAKE)
	cd Problem25 && $(MAKE)
	cd Problem26 && $(MAKE)
	cd Problem27 && $(MAKE)
	cd Problem28 && $(MAKE)
	cd Problem29 && $(MAKE)
	cd Problem30 && $(MAKE)
	cd Problem31 && $(MAKE)
	cd Problem32 && $(MAKE)
	cd Problem33 && $(MAKE)
	cd Problem34 && $(MAKE)


.PHONY: clean

clean:
	@make clean -C Problem1
	@make clean -C Problem2
	@make clean -C Problem3
	@make clean -C Problem4
	@make clean -C Problem5
	@make clean -C Problem6
	@make clean -C Problem7
	@make clean -C Problem8
	@make clean -C Problem9
	@make clean -C Problem10	
	@make clean -C Problem11
	@make clean -C Problem12
	@make clean -C Problem13
	@make clean -C Problem14
	@make clean -C Problem15
	@make clean -C Problem16
	@make clean -C Problem17
	@make clean -C Problem18
	@make clean -C Problem19
	@make clean -C Problem20
	@make clean -C Problem21
	@make clean -C Problem22
	@make clean -C Problem23
	@make clean -C Problem24
	@make clean -C Problem25
	@make clean -C Problem26
	@make clean -C Problem27
	@make clean -C Problem28
	@make clean -C Problem29
	@make clean -C Problem30
	@make clean -C Problem31
	@make clean -C Problem32
	@make clean -C Problem33
	@make clean -C Problem34
